version: "3.2"
services:
  web:
    build: .
    image: mshindal/tabchat:latest
    environment:
      - DATABASE_URL
      - PORT
      - USE_RECAPTCHA
      - RECAPTCHA_SECRET
      - TABCHAT_ENV
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:10.5
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  dbdata:
