name: main

on:
  push:
    branches:
    - master

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install NPM Dependencies
        working-directory: frontend/
        run: yarn install
      - name: Build frontend
        working-directory: frontend/
        env: 
          USE_RECAPTCHA: 'true'
          RECAPTCHA_SITEKEY: 6Lf8O7cUAAAAAJeUEaeSn9WMuOZFsudunf8Zxgd7
          SERVER_URL: https://www.tabchat.io
        run: yarn build
      - uses: actions/upload-artifact@master
        with: 
          name: extension
          path: frontend/extension/
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install NPM Dependencies
        working-directory: backend/
        run: yarn install
      - name: Build backend
        working-directory: backend/
        run: docker-compose build
      - name: Test backend
        working-directory: backend/
        run: yarn test
